---
stages:
  - setup
  - lint
  - test

default:
  image: python:3.10
  before_script:
    - make install
    - make test_install
  cache:
    paths:
      - ~/.cache/pip/

lint:
  stage: lint
  script:
    - pylint django_qos || exit 0

test:
  stage: test
  script:
    - make test
  coverage: '/TOTAL.+ ([0-9]{1,3}%)/'
  artifacts:
    name: "HTML coverage"
    when: on_success
    paths:
      - cs_web/coverage_html_report/
