# Generated by Django 3.2.18 on 2023-02-25 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('state', models.CharField(choices=[('success', 'Success'), ('failure', 'Failure'), ('error', 'Error')], max_length=20)),
                ('name', models.CharField(max_length=300)),
                ('doc', models.TextField(blank=True, max_length=2000, null=True)),
                ('path', models.CharField(max_length=300)),
                ('error', models.TextField(blank=True, max_length=20000, null=True)),
                ('error_msg', models.TextField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
