# Generated by Django 4.2.8 on 2024-09-12 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_qos_db', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('duration', models.FloatField()),
                ('method', models.CharField(max_length=20)),
                ('host', models.CharField(max_length=100)),
                ('path', models.CharField(max_length=500)),
                ('is_ajax', models.BooleanField()),
                ('using', models.CharField(blank=True, max_length=100, null=True)),
                ('queries', models.JSONField(blank=True, null=True)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('template_name', models.CharField(blank=True, max_length=500, null=True)),
                ('is_rendered', models.BooleanField()),
            ],
        ),
    ]
